# Generated by Django 5.2.11 on 2026-03-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_loginid', models.CharField(max_length=100)),
                ('algorithm_name', models.CharField(max_length=100)),
                ('input_text', models.CharField(max_length=5000)),
                ('prediction_result', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PredictionReport',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_loginid', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=50)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserActivityLog',
            },
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='role',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
