# Generated by Django 5.2.11 on 2026-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_predictionreport_useractivitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
