# Generated by Django 5.2.11 on 2026-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useractivitylog_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionreport',
            name='input_type',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
